//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `AuthRpoFalcon512` authentication component.
pub const AUTH_RPO_FALCON_512: &str =
    "0x9195f4c0deb2b6569ea9352e91ae78777dedd2690f9a19d29c8a254b88b62c4a";
