//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `AuthRpoFalcon512` authentication component.
pub const AUTH_RPO_FALCON_512: &str =
    "0xd2e461e91e9cf93810e96c30ed9e5ac6af6d992da5ca5276c960dcd220dcb6dd";
