name: "Task"
description: "Work item"
title: "[Task]: "
body:
  - type: markdown
    attributes:
      value: |
        A task should be less than a week worth of work!
  - type: textarea
    id: task-what
    attributes:
      label: "What should be done?"
      placeholder: "Support new way of importing accounts"
    validations:
      required: true
  - type: textarea
    id: task-how
    attributes:
      label: "How should it be done?"
      placeholder: "Add a function to the client which takes in an account definition filepath as a parameter"
    validations:
      required: true
  - type: textarea
    id: task-done
    attributes:
      label: "When is this task done?"
      placeholder: "The task is done when the client has a function to import account data from a binary file"
    validations:
      required: true
  - type: textarea
    id: task-related
    attributes:
      label: "Additional context"
      description: "Add context to the tasks. E.g. other related tasks or relevant dicussions on PRs/chats."
    validations:
      required: false
