use alloc::borrow::ToOwned;
use alloc::boxed::Box;
use alloc::collections::{BTreeMap, BTreeSet};
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::error::Error;
use miden_objects::asset::{Asset, AssetVault};

use miden_objects::account::{
    Account, AccountCode, AccountId, AccountStorage, StorageMap, StorageSlot, StorageSlotType,
};
use miden_objects::address::NetworkId;
use miden_objects::block::account_tree::AccountWitness;
use miden_objects::block::{BlockHeader, BlockNumber, ProvenBlock};
use miden_objects::crypto::merkle::{Forest, MerklePath, MmrProof, SmtProof};
use miden_objects::note::{NoteId, NoteScript, NoteTag, Nullifier};
use miden_objects::transaction::{ProvenTransaction, TransactionInputs};
use miden_objects::utils::Deserializable;
use miden_objects::{EMPTY_WORD, Word};
use miden_tx::utils::Serializable;
use miden_tx::utils::sync::RwLock;
use tonic::Status;
use tracing::info;

use super::domain::account::{AccountProof, AccountUpdateSummary};
use super::domain::note::FetchedNote;
use super::domain::nullifier::NullifierUpdate;
use super::generated::rpc::account_proof_request::AccountDetailRequest;
use super::generated::rpc::account_proof_request::account_detail_request::storage_map_detail_request;
use super::generated::rpc::{AccountProofRequest, SyncAccountVaultRequest};
use super::{
    Endpoint, FetchedAccount, NodeRpcClient, NodeRpcClientEndpoint, NoteSyncInfo, RpcError,
    StateSyncInfo,
};
use crate::rpc::domain::account_vault::AccountVaultInfo;
use crate::rpc::domain::storage_map::StorageMapInfo;
use crate::rpc::domain::transaction::TransactionsInfo;
use crate::rpc::errors::{AcceptHeaderError, GrpcError, RpcConversionError};
use crate::rpc::generated::rpc::account_proof_request::account_detail_request::StorageMapDetailRequest;
use crate::rpc::generated::rpc::{BlockRange, SyncStorageMapsRequest};
use crate::rpc::{AccountStateAt, NOTE_IDS_LIMIT, NULLIFIER_PREFIXES_LIMIT, generated as proto};
use crate::transaction::ForeignAccount;

mod api_client;
use api_client::api_client_wrapper::ApiClient;

// GRPC CLIENT
// ================================================================================================

/// Client for the Node RPC API using gRPC.
///
/// If the `tonic` feature is enabled, this client will use a `tonic::transport::Channel` to
/// communicate with the node. In this case the connection will be established lazily when the
/// first request is made.
/// If the `web-tonic` feature is enabled, this client will use a `tonic_web_wasm_client::Client`
/// to communicate with the node.
///
/// In both cases, the [`GrpcClient`] depends on the types inside the `generated` module, which
/// are generated by the build script and also depend on the target architecture.
pub struct GrpcClient {
    client: RwLock<Option<ApiClient>>,
    endpoint: String,
    timeout_ms: u64,
    genesis_commitment: RwLock<Option<Word>>,
}

impl GrpcClient {
    /// Returns a new instance of [`GrpcClient`] that'll do calls to the provided [`Endpoint`]
    /// with the given timeout in milliseconds.
    pub fn new(endpoint: &Endpoint, timeout_ms: u64) -> GrpcClient {
        GrpcClient {
            client: RwLock::new(None),
            endpoint: endpoint.to_string(),
            timeout_ms,
            genesis_commitment: RwLock::new(None),
        }
    }

    /// Takes care of establishing the RPC connection if not connected yet. It ensures that the
    /// `rpc_api` field is initialized and returns a write guard to it.
    async fn ensure_connected(&self) -> Result<ApiClient, RpcError> {
        if self.client.read().is_none() {
            self.connect().await?;
        }

        Ok(self.client.read().as_ref().expect("rpc_api should be initialized").clone())
    }

    /// Connects to the Miden node, setting the client API with the provided URL, timeout and
    /// genesis commitment.
    async fn connect(&self) -> Result<(), RpcError> {
        let genesis_commitment = *self.genesis_commitment.read();
        let new_client =
            ApiClient::new_client(self.endpoint.clone(), self.timeout_ms, genesis_commitment)
                .await?;
        let mut client = self.client.write();
        client.replace(new_client);

        Ok(())
    }
}

#[cfg_attr(not(target_arch = "wasm32"), async_trait::async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait::async_trait(?Send))]
impl NodeRpcClient for GrpcClient {
    /// Sets the genesis commitment for the client. If the client is already connected, it will be
    /// updated to use the new commitment on subsequent requests. If the client is not connected,
    /// the commitment will be stored and used when the client connects. If the genesis commitment
    /// is already set, this method does nothing.
    async fn set_genesis_commitment(&self, commitment: Word) -> Result<(), RpcError> {
        // Check if already set before doing anything else
        if self.genesis_commitment.read().is_some() {
            // Genesis commitment is already set, ignoring the new value.
            return Ok(());
        }

        // Store the commitment for future connections
        self.genesis_commitment.write().replace(commitment);

        // If a client is already connected, update it to use the new genesis commitment.
        // If not connected, the commitment will be used when connect() is called.
        let mut client_guard = self.client.write();
        if let Some(client) = client_guard.as_mut() {
            client.set_genesis_commitment(commitment);
        }

        Ok(())
    }

    async fn submit_proven_transaction(
        &self,
        proven_transaction: ProvenTransaction,
        transaction_inputs: TransactionInputs,
    ) -> Result<BlockNumber, RpcError> {
        let request = proto::transaction::ProvenTransaction {
            transaction: proven_transaction.to_bytes(),
            transaction_inputs: Some(transaction_inputs.to_bytes()),
        };

        let mut rpc_api = self.ensure_connected().await?;

        let api_response = rpc_api.submit_proven_transaction(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SubmitProvenTx, status)
        })?;

        Ok(BlockNumber::from(api_response.into_inner().block_num))
    }

    async fn get_block_header_by_number(
        &self,
        block_num: Option<BlockNumber>,
        include_mmr_proof: bool,
    ) -> Result<(BlockHeader, Option<MmrProof>), RpcError> {
        let request = proto::rpc::BlockHeaderByNumberRequest {
            block_num: block_num.as_ref().map(BlockNumber::as_u32),
            include_mmr_proof: Some(include_mmr_proof),
        };

        info!("Calling GetBlockHeaderByNumber: {:?}", request);

        let mut rpc_api = self.ensure_connected().await?;

        let api_response = rpc_api.get_block_header_by_number(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::GetBlockHeaderByNumber, status)
        })?;

        let response = api_response.into_inner();

        let block_header: BlockHeader = response
            .block_header
            .ok_or(RpcError::ExpectedDataMissing("BlockHeader".into()))?
            .try_into()?;

        let mmr_proof = if include_mmr_proof {
            let forest = response
                .chain_length
                .ok_or(RpcError::ExpectedDataMissing("ChainLength".into()))?;
            let merkle_path: MerklePath = response
                .mmr_path
                .ok_or(RpcError::ExpectedDataMissing("MmrPath".into()))?
                .try_into()?;

            Some(MmrProof {
                forest: Forest::new(usize::try_from(forest).expect("u64 should fit in usize")),
                position: block_header.block_num().as_usize(),
                merkle_path,
            })
        } else {
            None
        };

        Ok((block_header, mmr_proof))
    }

    async fn get_notes_by_id(&self, note_ids: &[NoteId]) -> Result<Vec<FetchedNote>, RpcError> {
        let mut notes = Vec::with_capacity(note_ids.len());
        for chunk in note_ids.chunks(NOTE_IDS_LIMIT) {
            let request = proto::note::NoteIdList {
                ids: chunk.iter().map(|id| (*id).into()).collect(),
            };

            let mut rpc_api = self.ensure_connected().await?;

            let api_response = rpc_api.get_notes_by_id(request).await.map_err(|status| {
                RpcError::from_grpc_error(NodeRpcClientEndpoint::GetNotesById, status)
            })?;

            let response_notes = api_response
                .into_inner()
                .notes
                .into_iter()
                .map(FetchedNote::try_from)
                .collect::<Result<Vec<FetchedNote>, RpcConversionError>>()?;

            notes.extend(response_notes);
        }
        Ok(notes)
    }

    /// Sends a sync state request to the Miden node, validates and converts the response
    /// into a [`StateSyncInfo`] struct.
    async fn sync_state(
        &self,
        block_num: BlockNumber,
        account_ids: &[AccountId],
        note_tags: &BTreeSet<NoteTag>,
    ) -> Result<StateSyncInfo, RpcError> {
        let account_ids = account_ids.iter().map(|acc| (*acc).into()).collect();

        let note_tags = note_tags.iter().map(|&note_tag| note_tag.into()).collect();

        let request = proto::rpc::SyncStateRequest {
            block_num: block_num.as_u32(),
            account_ids,
            note_tags,
        };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.sync_state(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncState, status)
        })?;
        response.into_inner().try_into()
    }

    /// Sends a `GetAccountDetailsRequest` to the Miden node, and extracts an [`FetchedAccount`]
    /// from the `GetAccountDetailsResponse` response.
    ///
    /// # Errors
    ///
    /// This function will return an error if:
    ///
    /// - There was an error sending the request to the node.
    /// - The answer had a `None` for one of the expected fields (`account`, `summary`,
    ///   `account_commitment`, `details`).
    /// - There is an error during [Account] deserialization.
    async fn get_account_details(&self, account_id: AccountId) -> Result<FetchedAccount, RpcError> {
        let details_request = {
            if account_id.is_private() {
                None
            } else {
                Some(AccountDetailRequest {
                    code_commitment: Some(EMPTY_WORD.into()),
                    asset_vault_commitment: Some(EMPTY_WORD.into()),
                    storage_maps: vec![],
                })
            }
        };

        let request = AccountProofRequest {
            account_id: Some(account_id.into()),
            block_num: None,
            details: details_request,
        };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.get_account_proof(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::GetAccountDetails, status)
        });

        let response = response?.into_inner();

        let Some(witness) = response.witness else {
            return Err(RpcError::ExpectedDataMissing(
                "GetAccountDetails returned an account without witness".to_owned(),
            ));
        };

        let Some(commitment) = witness.commitment else {
            return Err(RpcError::ExpectedDataMissing(
                "GetAccountDetails returned an account witness without commitment".to_owned(),
            ));
        };

        let Some(block_number) = response.block_num.map(|bn| bn.block_num) else {
            return Err(RpcError::ExpectedDataMissing(
                "GetAccountDetails returned an account without a matching block number for the witness".to_owned(),
            ));
        };

        let commitment = commitment.try_into()?;

        let update_summary = AccountUpdateSummary::new(commitment, block_number);

        if account_id.is_private() {
            Ok(FetchedAccount::new_private(account_id, update_summary))
        } else {
            // FIXME:
            // - Double check passing an empty map is OK.
            // - We probably want to split the steps below into one or more functions
            let details = response
                .details
                .ok_or(RpcError::ExpectedDataMissing(
                    "GetAccountDetails returned a public account without details".to_owned(),
                ))
                .and_then(|details| details.into_domain(&Default::default()))?;
            let account_id = details.header.id();
            let nonce = details.header.nonce();
            let assets: Vec<Asset> = {
                if details.vault_details.too_many_assets {
                    let req = SyncAccountVaultRequest {
                        // FIXME: What should this parameter be?
                        block_range: None,
                        account_id: Some(details.header.id().clone().into()),
                    };
                    rpc_api
                        .sync_account_vault(req)
                        .await
                        .map_err(|status| {
                            RpcError::from_grpc_error(
                                NodeRpcClientEndpoint::SyncAccountVault,
                                status,
                            )
                        })?
                        .into_inner()
                        .updates
                        .into_iter()
                        .map(|update| Asset::try_from(update.asset.unwrap()).unwrap())
                        .collect()
                } else {
                    // FIXME: Remove unwrap
                    details.vault_details.assets
                }
            };
            let response_slots = details.storage_details.header.slots();
            let map_details = details
                .storage_details
                .map_details
                .into_iter()
                .map(|map_detail| {
                    (map_detail.slot_name, (map_detail.too_many_entries, map_detail.entries))
                })
                .collect::<BTreeMap<_, _>>();
            let mut slots = vec![];
            for (index, slot_header) in response_slots.enumerate() {
                match slot_header.slot_type() {
                    // FIXME:
                    // - Should we specify a BlockRange?.
                    // - Remove unwraps.
                    // - Avoid nesting so much.
                    // - Each entry from the storage details has a
                    // 'too_many_entries' should this be only a single request?
                    // - Avoid using 'extend' 2 times.
                    StorageSlotType::Value => {
                        slots.push(miden_objects::account::StorageSlot::with_value(
                            slot_header.name().clone(),
                            slot_header.value(),
                        ))
                    },
                    StorageSlotType::Map => {
                        let (too_many_entries, entries) = map_details
                            .get(slot_header.name())
                            // FIXME: Remove unwrap
                            .unwrap();
                        let mut map_entries = vec![];
                        if *too_many_entries {
                            map_entries.extend(
                                rpc_api
                            .sync_storage_maps(SyncStorageMapsRequest {
                                block_range: None,
                                account_id: Some(account_id.clone().into()),
                            })
                            .await
                        .map_err(|status| {
                            RpcError::from_grpc_error(
                                NodeRpcClientEndpoint::SyncAccountVault,
                                status,
                            )
                        })?
                        // FIXME: SyncStorageMapsResponse has 'pagination' field, should we
                        // do something with it?
                            .into_inner()
                            .updates
                            .into_iter()
                        // FIXME:
                        // - Avoid these unwraps
                        // - Use better names
                            .map(|u| {
                                let key: Word = u.key.unwrap().try_into().unwrap();
                                let value: Word = u.value.unwrap().try_into().unwrap();
                                (key, value)
                            }),
                            )
                        } else {
                            map_entries.extend(entries.into_iter().map(|e| {
                                let key: Word = e.key.into();
                                let value: Word = e.value.into();
                                (key, value)
                            }))
                        }

                        slots.push(miden_objects::account::StorageSlot::with_map(
                            slot_header.name().clone(),
                            StorageMap::with_entries(map_entries).unwrap(),
                        ));
                    },
                }
            }
            // FIXME: Is this correct?
            let seed = None;
            let account = Account::new(
                account_id,
                // FIXME: Remove unwraps
                AssetVault::new(&assets).unwrap(),
                AccountStorage::new(slots).unwrap(),
                details.code,
                nonce,
                seed,
            )
            .unwrap();
            Ok(FetchedAccount::new_public(account, update_summary))
        }
    }

    /// Sends a `GetAccountProof` request to the Miden node, and extracts the [AccountProof]
    /// from the response, as well as the block number that it was retrieved for.
    ///
    /// # Errors
    ///
    /// This function will return an error if:
    ///
    /// - The requested Account isn't returned by the node.
    /// - There was an error sending the request to the node.
    /// - The answer had a `None` for one of the expected fields.
    /// - There is an error during storage deserialization.
    async fn get_account_proof(
        &self,
        foreign_account: ForeignAccount,
        account_state: AccountStateAt,
        known_account_code: Option<AccountCode>,
    ) -> Result<(BlockNumber, AccountProof), RpcError> {
        let mut known_codes_by_commitment: BTreeMap<Word, AccountCode> = BTreeMap::new();
        if let Some(account_code) = known_account_code {
            known_codes_by_commitment.insert(account_code.commitment(), account_code);
        }

        let mut rpc_api = self.ensure_connected().await?;

        // Request proofs one-by-one using the singular API
        let account_id = foreign_account.account_id();
        let storage_requirements = foreign_account.storage_slot_requirements();

        let storage_maps: Vec<StorageMapDetailRequest> = storage_requirements.clone().into();

        // Only request details for public accounts; include known code commitment for this
        // account when available
        let account_details = if account_id.is_public() {
            Some(proto::rpc::account_proof_request::AccountDetailRequest {
                code_commitment: Some(EMPTY_WORD.into()),
                // TODO: implement a way to request asset vaults
                // https://github.com/0xMiden/miden-client/issues/1412
                asset_vault_commitment: None,
                storage_maps,
            })
        } else {
            None
        };

        let block_num = match account_state {
            AccountStateAt::Block(number) => Some(number.into()),
            AccountStateAt::ChainTip => None,
        };

        let request = proto::rpc::AccountProofRequest {
            account_id: Some(account_id.into()),
            block_num,
            details: account_details,
        };

        let response = rpc_api
            .get_account_proof(request)
            .await
            .map_err(|status| {
                RpcError::from_grpc_error(NodeRpcClientEndpoint::GetAccountProofs, status)
            })?
            .into_inner();

        let account_witness: AccountWitness = response
            .witness
            .ok_or(RpcError::ExpectedDataMissing("AccountWitness".to_string()))?
            .try_into()?;

        // For public accounts, details should be present when requested
        let headers = if account_witness.id().is_public() {
            Some(
                response
                    .details
                    .ok_or(RpcError::ExpectedDataMissing("Account.Details".to_string()))?
                    .into_domain(&known_codes_by_commitment)?,
            )
        } else {
            None
        };

        let proof = AccountProof::new(account_witness, headers)
            .map_err(|err| RpcError::InvalidResponse(err.to_string()))?;

        let block_num = response
            .block_num
            .ok_or(RpcError::ExpectedDataMissing("response block num".to_string()))?
            .block_num
            .into();

        Ok((block_num, proof))
    }

    /// Sends a `SyncNoteRequest` to the Miden node, and extracts a [`NoteSyncInfo`] from the
    /// response.
    async fn sync_notes(
        &self,
        block_num: BlockNumber,
        block_to: Option<BlockNumber>,
        note_tags: &BTreeSet<NoteTag>,
    ) -> Result<NoteSyncInfo, RpcError> {
        let note_tags = note_tags.iter().map(|&note_tag| note_tag.into()).collect();

        let block_range = Some(BlockRange {
            block_from: block_num.as_u32(),
            block_to: block_to.map(|b| b.as_u32()),
        });

        let request = proto::rpc::SyncNotesRequest { block_range, note_tags };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.sync_notes(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncNotes, status)
        })?;

        response.into_inner().try_into()
    }

    async fn sync_nullifiers(
        &self,
        prefixes: &[u16],
        block_num: BlockNumber,
        block_to: Option<BlockNumber>,
    ) -> Result<Vec<NullifierUpdate>, RpcError> {
        const MAX_ITERATIONS: u32 = 1000; // Safety limit to prevent infinite loops

        let mut all_nullifiers = BTreeSet::new();

        // Establish RPC connection once before the loop
        let mut rpc_api = self.ensure_connected().await?;

        // If the prefixes are too many, we need to chunk them into smaller groups to avoid
        // violating the RPC limit.
        'chunk_nullifiers: for chunk in prefixes.chunks(NULLIFIER_PREFIXES_LIMIT) {
            let mut current_block_from = block_num.as_u32();

            for _ in 0..MAX_ITERATIONS {
                let request = proto::rpc::SyncNullifiersRequest {
                    nullifiers: chunk.iter().map(|&x| u32::from(x)).collect(),
                    prefix_len: 16,
                    block_range: Some(BlockRange {
                        block_from: current_block_from,
                        block_to: block_to.map(|b| b.as_u32()),
                    }),
                };

                let response = rpc_api.sync_nullifiers(request).await.map_err(|status| {
                    RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncNullifiers, status)
                })?;
                let response = response.into_inner();

                // Convert nullifiers for this batch
                let batch_nullifiers = response
                    .nullifiers
                    .iter()
                    .map(TryFrom::try_from)
                    .collect::<Result<Vec<NullifierUpdate>, _>>()
                    .map_err(|err| RpcError::InvalidResponse(err.to_string()))?;

                all_nullifiers.extend(batch_nullifiers);

                // Check if we need to fetch more pages
                if let Some(page) = response.pagination_info {
                    // Ensure we're making progress to avoid infinite loops
                    if page.block_num < current_block_from {
                        return Err(RpcError::InvalidResponse(
                            "invalid pagination: block_num went backwards".to_string(),
                        ));
                    }

                    // Calculate target block as minimum between block_to and chain_tip
                    let target_block =
                        block_to.map_or(page.chain_tip, |b| b.as_u32().min(page.chain_tip));

                    if page.block_num >= target_block {
                        // No pagination info or we've reached/passed the target so we're done
                        continue 'chunk_nullifiers;
                    }
                    current_block_from = page.block_num + 1;
                }
            }
            // If we exit the loop, we've hit the iteration limit
            return Err(RpcError::InvalidResponse(
                "too many pagination iterations, possible infinite loop".to_string(),
            ));
        }
        Ok(all_nullifiers.into_iter().collect::<Vec<_>>())
    }

    async fn check_nullifiers(&self, nullifiers: &[Nullifier]) -> Result<Vec<SmtProof>, RpcError> {
        let mut proofs: Vec<SmtProof> = Vec::with_capacity(nullifiers.len());
        for chunk in nullifiers.chunks(NULLIFIER_PREFIXES_LIMIT) {
            let request = proto::rpc::NullifierList {
                nullifiers: chunk.iter().map(|nul| nul.as_word().into()).collect(),
            };

            let mut rpc_api = self.ensure_connected().await?;

            let response = rpc_api.check_nullifiers(request).await.map_err(|status| {
                RpcError::from_grpc_error(NodeRpcClientEndpoint::CheckNullifiers, status)
            })?;

            let mut response = response.into_inner();
            let chunk_proofs = response
                .proofs
                .iter_mut()
                .map(|r| r.to_owned().try_into())
                .collect::<Result<Vec<SmtProof>, RpcConversionError>>()?;
            proofs.extend(chunk_proofs);
        }
        Ok(proofs)
    }

    async fn get_block_by_number(&self, block_num: BlockNumber) -> Result<ProvenBlock, RpcError> {
        let request = proto::blockchain::BlockNumber { block_num: block_num.as_u32() };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.get_block_by_number(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::GetBlockByNumber, status)
        })?;

        let response = response.into_inner();
        let block =
            ProvenBlock::read_from_bytes(&response.block.ok_or(RpcError::ExpectedDataMissing(
                "GetBlockByNumberResponse.block".to_string(),
            ))?)?;

        Ok(block)
    }

    async fn get_note_script_by_root(&self, root: Word) -> Result<NoteScript, RpcError> {
        let request = proto::note::NoteRoot { root: Some(root.into()) };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.get_note_script_by_root(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::GetNoteScriptByRoot, status)
        })?;

        let response = response.into_inner();
        let note_script = NoteScript::try_from(
            response
                .script
                .ok_or(RpcError::ExpectedDataMissing("GetNoteScriptByRoot.script".to_string()))?,
        )?;

        Ok(note_script)
    }

    async fn sync_storage_maps(
        &self,
        block_from: BlockNumber,
        block_to: Option<BlockNumber>,
        account_id: AccountId,
    ) -> Result<StorageMapInfo, RpcError> {
        let block_range = Some(BlockRange {
            block_from: block_from.as_u32(),
            block_to: block_to.map(|b| b.as_u32()),
        });

        let request = proto::rpc::SyncStorageMapsRequest {
            block_range,
            account_id: Some(account_id.into()),
        };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.sync_storage_maps(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncStorageMaps, status)
        })?;

        response.into_inner().try_into()
    }

    async fn sync_account_vault(
        &self,
        block_from: BlockNumber,
        block_to: Option<BlockNumber>,
        account_id: AccountId,
    ) -> Result<AccountVaultInfo, RpcError> {
        let block_range = Some(BlockRange {
            block_from: block_from.as_u32(),
            block_to: block_to.map(|b| b.as_u32()),
        });

        let request = proto::rpc::SyncAccountVaultRequest {
            block_range,
            account_id: Some(account_id.into()),
        };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.sync_account_vault(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncAccountVault, status)
        })?;

        response.into_inner().try_into()
    }

    async fn sync_transactions(
        &self,
        block_from: BlockNumber,
        block_to: Option<BlockNumber>,
        account_ids: Vec<AccountId>,
    ) -> Result<TransactionsInfo, RpcError> {
        let block_range = Some(BlockRange {
            block_from: block_from.as_u32(),
            block_to: block_to.map(|b| b.as_u32()),
        });

        let account_ids = account_ids.iter().map(|acc_id| (*acc_id).into()).collect();

        let request = proto::rpc::SyncTransactionsRequest { block_range, account_ids };

        let mut rpc_api = self.ensure_connected().await?;

        let response = rpc_api.sync_transactions(request).await.map_err(|status| {
            RpcError::from_grpc_error(NodeRpcClientEndpoint::SyncTransactions, status)
        })?;

        response.into_inner().try_into()
    }

    async fn get_network_id(&self) -> Result<NetworkId, RpcError> {
        let endpoint_str: &str = &self.endpoint.clone();
        let endpoint: Endpoint =
            Endpoint::try_from(endpoint_str).map_err(RpcError::InvalidNodeEndpoint)?;
        Ok(endpoint.to_network_id())
    }
}

// ERRORS
// ================================================================================================

impl RpcError {
    pub fn from_grpc_error(endpoint: NodeRpcClientEndpoint, status: Status) -> Self {
        if let Some(accept_error) = AcceptHeaderError::try_from_message(status.message()) {
            return Self::AcceptHeaderError(accept_error);
        }

        let error_kind = GrpcError::from(&status);
        let source = Box::new(status) as Box<dyn Error + Send + Sync + 'static>;

        Self::GrpcError {
            endpoint,
            error_kind,
            source: Some(source),
        }
    }
}

impl From<&Status> for GrpcError {
    fn from(status: &Status) -> Self {
        GrpcError::from_code(status.code() as i32, Some(status.message().to_string()))
    }
}

#[cfg(test)]
mod tests {
    use std::boxed::Box;

    use miden_objects::Word;

    use super::GrpcClient;
    use crate::rpc::{Endpoint, NodeRpcClient};

    fn assert_send_sync<T: Send + Sync>() {}

    #[test]
    fn is_send_sync() {
        assert_send_sync::<GrpcClient>();
        assert_send_sync::<Box<dyn NodeRpcClient>>();
    }

    // Function that returns a `Send` future from a dynamic trait that must be `Sync`.
    async fn dyn_trait_send_fut(client: Box<dyn NodeRpcClient>) {
        // This won't compile if `get_block_header_by_number` doesn't return a `Send+Sync` future.
        let res = client.get_block_header_by_number(None, false).await;
        assert!(res.is_ok());
    }

    #[tokio::test]
    async fn future_is_send() {
        let endpoint = &Endpoint::devnet();
        let client = GrpcClient::new(endpoint, 10000);
        let client: Box<GrpcClient> = client.into();
        tokio::task::spawn(async move { dyn_trait_send_fut(client).await });
    }

    #[tokio::test]
    async fn set_genesis_commitment_sets_the_commitment_when_its_not_already_set() {
        let endpoint = &Endpoint::devnet();
        let client = GrpcClient::new(endpoint, 10000);

        assert!(client.genesis_commitment.read().is_none());

        let commitment = Word::default();
        client.set_genesis_commitment(commitment).await.unwrap();

        assert_eq!(client.genesis_commitment.read().unwrap(), commitment);
    }

    #[tokio::test]
    async fn set_genesis_commitment_does_nothing_if_the_commitment_is_already_set() {
        use miden_objects::Felt;

        let endpoint = &Endpoint::devnet();
        let client = GrpcClient::new(endpoint, 10000);

        let initial_commitment = Word::default();
        client.set_genesis_commitment(initial_commitment).await.unwrap();

        let new_commitment = Word::from([Felt::new(1), Felt::new(2), Felt::new(3), Felt::new(4)]);
        client.set_genesis_commitment(new_commitment).await.unwrap();

        assert_eq!(client.genesis_commitment.read().unwrap(), initial_commitment);
    }

    #[tokio::test]
    async fn set_genesis_commitment_updates_the_client_if_already_connected() {
        let endpoint = &Endpoint::devnet();
        let client = GrpcClient::new(endpoint, 10000);

        // "Connect" the client
        client.connect().await.unwrap();

        let commitment = Word::default();
        client.set_genesis_commitment(commitment).await.unwrap();

        assert_eq!(client.genesis_commitment.read().unwrap(), commitment);
        assert!(client.client.read().as_ref().is_some());
    }
}
