## USAGE:
## ================================================================================================
# - endpoint: tuple indicating the protocol (http, https), the host, and (optionally) the port where the node is listening.
# - timeout: timeout in ms for the rpc requests against the node.

endpoint = { protocol = "https", host = "rpc.testnet.miden.io" }
timeout = 10000
