name: Check
on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust
        run: |
          rustup update --no-self-update nightly
      - name: make - check
        run: make check

  check-wasm:
    name: Check WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust with rustfmt
        run: |
          rustup update --no-self-update nightly
      - name: make - check-wasm
        run: make check-wasm
