# This workflow checks if the version number in the `package.json` file of the `web-client` 
# package has been bumped when there are changes in the `web-client` or `web_store` 
# directories. If the version number has not been bumped, it fails the workflow with 
# an error message.

name: Enforce SDK Version Bump

on:
  pull_request:
    branches: [ next ]
    types: [ opened, reopened, synchronize, labeled, unlabeled ]

jobs:
  enforce-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gather changed files
        id: detect
        # pass the PR base branch into the script
        run: bash ./scripts/detect-web-client-changes.sh "${{ github.event.pull_request.base.ref }}"
      
      # new step: detect a bypass label on the PR
      - name: Check for bypass label
        id: skip
        uses: actions/github-script@v6
        with:
          script: |
            // list all PR labels
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const bypass = labels.includes('bypass-sdk-version-bump');
            core.setOutput('bypass', bypass);

      # Only if code changed do we compare versions
      - name: Fetch base package.json version
        if: steps.detect.outputs.code_changed == 'true'
        id: base
        uses: actions/github-script@v6
        with:
          script: |
            const resp = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              path:  'crates/web-client/package.json',
              ref:   context.payload.pull_request.base.ref
            });
            const content = Buffer.from(resp.data.content, 'base64').toString();
            const { version } = JSON.parse(content);
            core.setOutput('version', version);

      - name: Read head package.json version
        if: steps.detect.outputs.code_changed == 'true'
        id: head
        run: |
          VER=$(node -p "require('./crates/web-client/package.json').version")
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Fail if version not bumped
        if: >
          steps.detect.outputs.code_changed == 'true' &&
          steps.base.outputs.version == steps.head.outputs.version &&
          steps.skip.outputs.bypass != 'true'
        run: |
          echo "::error ::You modified code under web-client or web_store but did not bump the version in crates/web-client/package.json. Bump the version or add the 'bypass-sdk-version-bump' label to the PR."
          echo "::error ::Base and head version are both '${{ steps.head.outputs.version }}'."
          exit 1

      - name: Success
        run: echo "✅ OK - either no relevant code changes, version was bumped, or bypass label was applied."
